image: 'python:3.6.9-buster'

flake8:
  script:
    - pip install flake8==3.7.9
    - flake8

migrations:
  services:
    - name: postgres:11.5
      alias: db
  variables:
    POSTGRES_DB: ci_db
    POSTGRES_USER: ci_runner
    POSTGRES_PASSWORD: "ci_pass"
    MOSE_DATABASE_NAME: "$POSTGRES_DB"
    MOSE_DATABASE_USER: "$POSTGRES_USER"
    MOSE_DATABASE_PASSWORD: "$POSTGRES_PASSWORD"
    MOSE_DATABASE_HOST: 'db'
  script:
    - pip install -r requirements.txt
    - pip freeze
    # exits with a non-zero status when model changes without migrations are detected.
    - ./manage.py makemigrations --check
    - ./manage.py migrate
    - ./manage.py populate_db

tests:
  services:
    - name: postgres:11.5
      alias: db
  variables:
    POSTGRES_DB: ci_db
    POSTGRES_USER: ci_runner
    POSTGRES_PASSWORD: "ci_pass"
    MOSE_DATABASE_NAME: "$POSTGRES_DB"
    MOSE_DATABASE_USER: "$POSTGRES_USER"
    MOSE_DATABASE_PASSWORD: "$POSTGRES_PASSWORD"
    MOSE_DATABASE_HOST: 'db'
  script:
    - pip install -r requirements.txt -r requirements-tests.txt
    - coverage run --source='.' manage.py test --no-input
    - coverage report
    - coveralls
