[tool.black]
line-length = 88
target-version = ['py36']
exclude = '''
/(\.eggs|\.git|\.hg|\.mypy|_cache|\.nox|\.tox|\.venv|\.svn|_build|buck-out|build|dist)/
| /wizuber/migrations/
'''

[tool.isort]
multi_line_output = 3
include_trailing_comma = true
#force_grid_wrap = 0
use_parentheses = true
line_length = 88
skip = "wizuber/migrations"
