version: '3.7'

services:
  web:
    build:
      dockerfile: docker/web.dockerfile
      context: ..
    environment:
      - DATABASE_HOST=pg
    volumes:
      - ..:/code
    ports:
      - 8000:8000
    depends_on:
      - pg

  pg:
    build:
      dockerfile: database.dockerfile
      context: .
    ports:
      - "5432:5432"
    volumes:
      - ./db-scripts:/scripts
    environment:
      POSTGRES_DB: "wizuber"
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "secret_pass"
    restart: on-failure
