version: '3.7'

services:
  web:
    build:
      dockerfile: docker/web.dockerfile
      context: ..
    environment:
      MOSE_DATABASE_NAME: "wizuber_db"
      MOSE_DATABASE_USER: "wizuber_user"
      MOSE_DATABASE_PASSWORD: "wizuber_pass"
      MOSE_DATABASE_HOST: "db"
      MOSE_DATABASE_PORT: "5432"
    volumes:
      - ..:/code
    ports:
      - 8000:8000
    depends_on:
      - db

  db:
    build:
      dockerfile: database.dockerfile
      context: .
    ports:
      - "5432:5432"
    volumes:
      - ./db-scripts:/scripts
    environment:
      POSTGRES_DB: "wizuber_db"
      POSTGRES_USER: "wizuber_user"
      POSTGRES_PASSWORD: "wizuber_pass"
    restart: on-failure
