version: '3.7'

services:
  pg:
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - "5432:5432"
    volumes:
      - ./scripts:/scripts
    environment:
      POSTGRES_DB: "wizuber"
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "secret_pass"
    restart: on-failure
