version: '3.7'

services:
  pg:
    image: postgres:11.2
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: "wizuber"
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "secret_pass"
    restart: on-failure
