# Generated by Django 2.2.1 on 2019-05-10 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wizuber', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RightsSupport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': (('customer_rights', 'Global customer rights'), ('wizard_rights', 'Global wizard rights')),
                'managed': False,
            },
        ),
    ]
