# Generated by Django 2.2.6 on 2019-11-10 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wizuber', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spirit',
            name='master',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wizuber.Wizard'),
        ),
    ]
