# Generated by Django 2.2.6 on 2019-11-04 17:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import wizuber.models


class Migration(migrations.Migration):

    dependencies = [
        ('wizuber', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Spirit',
            fields=[
                ('wizuberuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('grade', models.CharField(choices=[('IMP', 'Imp'), ('FOLIOT', 'Foliot'), ('DJINNI', 'Djinni'), ('AFRIT', 'Afrit'), ('MARID', 'Marid')], max_length=6)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('wizuber.wizuberuser',),
            managers=[
                ('objects', wizuber.models.PolymorphicUserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('wizuberuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('wizuber.wizuberuser',),
            managers=[
                ('objects', wizuber.models.PolymorphicUserManager()),
            ],
        ),
    ]
