# Generated by Django 2.2.6 on 2019-11-24 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wizuber', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wish',
            name='status',
            field=models.CharField(choices=[('NEW', 'New'), ('ACTIVE', 'Active'), ('WORK', 'Work'), ('ON_SPIRIT', 'On Spirit'), ('READY', 'Ready'), ('CLOSED', 'Closed')], default='NEW', max_length=9),
        ),
    ]
