# Generated by Django 2.2.6 on 2019-11-24 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wizuber', '0002_auto_20191124_0814'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='baseartifact',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='candleartifact',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='pentacleartifact',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='spirit',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='spiritartifact',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='wish',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='wizard',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='wizuberuser',
            options={'ordering': ['id']},
        ),
    ]
