# Generated by Django 2.2.1 on 2019-05-12 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wizuber', '0002_rightssupport'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rightssupport',
            options={'managed': False, 'permissions': (('customer', 'Global customer rights'), ('wizard', 'Global wizard rights'))},
        ),
    ]
