# Generated by Django 2.2.6 on 2019-11-10 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wizuber', '0002_auto_20191110_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wish',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_wishes', to='wizuber.Customer'),
        ),
        migrations.AlterField(
            model_name='wish',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owned_wishes', to='wizuber.Wizard'),
        ),
    ]
