# Generated by Django 2.2.6 on 2019-11-04 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wizuber', '0002_spirit_student'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rightssupport',
            options={'managed': False, 'permissions': (('customer_perm', 'Global customer rights'), ('wizard_perm', 'Global wizard rights'), ('student_perm', 'Global student rights'), ('spirit_perm', 'Global spirit rights'))},
        ),
    ]
