# Generated by Django 2.2.1 on 2019-05-12 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wizuber', '0003_auto_20190512_1339'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishes',
            name='status',
            field=models.CharField(choices=[('NEW', 'New'), ('ACTIVE', 'Active'), ('WORK', 'Work'), ('READY', 'Ready'), ('CLOSED', 'Closed'), ('CANCELED', 'Canceled')], default='NEW', max_length=8),
        ),
    ]
