# Generated by Django 2.2.6 on 2019-11-16 15:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wizuber', '0004_wish_assigned_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='balance',
            field=models.PositiveIntegerField(default=500),
        ),
        migrations.AddField(
            model_name='wish',
            name='price',
            field=models.PositiveIntegerField(default=50, validators=[django.core.validators.MinValueValidator(limit_value=1)]),
        ),
        migrations.AddField(
            model_name='wizard',
            name='balance',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
