# Generated by Django 2.2.6 on 2019-11-30 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wizuber', '0005_auto_20191124_1931'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pentacleartifact',
            name='description',
        ),
    ]
