# Generated by Django 2.2.6 on 2019-11-17 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wizuber', '0005_auto_20191116_1503'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseArtifact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artifacts', to='wizuber.Wish')),
            ],
        ),
        migrations.CreateModel(
            name='CandleArtifact',
            fields=[
                ('baseartifact_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wizuber.BaseArtifact')),
                ('size', models.CharField(choices=[('LARGE', 'large'), ('MEDIUM', 'medium'), ('SMALL', 'small')], default='MEDIUM', max_length=6)),
                ('material', models.CharField(choices=[('TALLOW', 'tallow'), ('BEESWAX', 'beeswax'), ('PARAFFIN', 'paraffin')], default='TALLOW', max_length=8)),
            ],
            bases=('wizuber.baseartifact',),
        ),
        migrations.CreateModel(
            name='PentacleArtifact',
            fields=[
                ('baseartifact_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wizuber.BaseArtifact')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('size', models.CharField(choices=[('LARGE', 'large'), ('MEDIUM', 'medium'), ('SMALL', 'small')], default='MEDIUM', max_length=6)),
            ],
            bases=('wizuber.baseartifact',),
        ),
        migrations.CreateModel(
            name='SpiritArtifact',
            fields=[
                ('baseartifact_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wizuber.BaseArtifact')),
                ('spirit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spirit_artifacts', to='wizuber.Spirit')),
            ],
            bases=('wizuber.baseartifact',),
        ),
    ]
