# Generated by Django 2.2.6 on 2019-11-23 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wizuber', '0007_auto_20191123_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spiritartifact',
            name='spirit',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='spirit_artifact', to='wizuber.Spirit'),
        ),
    ]
